stages:
  - build
  - upload
  - release

variables:
  DEB_FILE_LATEST: "ostserver_latest_amd64.deb"
  DEB_FILE_TAG: "ostserver_${CI_COMMIT_TAG}_amd64.deb"
  PACKAGE_REGISTRY_LATEST: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/latest/latest"
  PACKAGE_REGISTRY_TAG: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_COMMIT_TAG}/${CI_COMMIT_TAG}"


build-job:
  stage: build
  image: ubuntu:24.04
  script:
    - ./CI/CI-build.sh
  artifacts:
    paths:
      - ${DEB_FILE_LATEST}
      - ${DEB_FILE_TAG}
      - server.log
      - ws.log
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/'

upload-job-tag:
  stage: upload
  dependencies:
    - build-job
  image: curlimages/curl:latest
  script:
    - |
      curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${DEB_FILE_TAG} ${PACKAGE_REGISTRY_TAG}/${DEB_FILE_TAG}
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/'

upload-job-latest:
  stage: upload
  dependencies:
    - build-job
  image: curlimages/curl:latest
  script:
    - echo "Dummy"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'

release-job-tag:
  stage: release
  dependencies:
    - upload-job-tag
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${DEB_FILE_TAG}\",\"url\":\"${PACKAGE_REGISTRY_TAG}/${DEB_FILE_TAG}\"}" 
  rules:
      - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/'

release-job-latest:
  stage: release
  dependencies:
    - upload-job-latest
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - sh ./CI/CI-upload-release-latest.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'

