var searchData=
[
  ['2_20—_20correction_20loop_20continuous_20no_20mount_20moves_0',['Phase 2 — correction loop (continuous, no mount moves)',['../md_src_2modules_2polar_2polar-analysis.html#autotoc_md81',1,'']]],
  ['2_20coordinate_20conversion_20chain_1',['2. Coordinate conversion chain',['../md_src_2modules_2polar_2polar-analysis.html#autotoc_md73',1,'']]],
  ['2_20correction_20computation_20tt_20gmath_20cpp_20tt_2',['2. Correction computation (&lt;tt&gt;gmath.cpp&lt;/tt&gt;)',['..//home/runner/work/OST/OST/src/modules/guider/guider-ekos-analysis.fr.md#autotoc_md16',1,'']]],
  ['2_20division_20by_20zero_20in_20tt_20matchindexes_20tt_3',['2. Division by zero in &lt;tt&gt;matchIndexes()&lt;/tt&gt;',['../md_src_2modules_2guider_2OST-guider-analysis.html#autotoc_md33',1,'']]],
  ['20_4',['20',['..//home/runner/work/OST/OST/src/modules/allsky/allsky.fr.md#autotoc_md1',1,'weight : 20'],['..//home/runner/work/OST/OST/src/modules/focus/focus.fr.md#autotoc_md3',1,'weight : 20'],['..//home/runner/work/OST/OST/src/modules/guider/guider-ekos-analysis.fr.md#autotoc_md5',1,'weight : 20'],['..//home/runner/work/OST/OST/src/modules/guider/guider.fr.md#autotoc_md27',1,'weight : 20'],['..//home/runner/work/OST/OST/src/modules/inspector/inspector.fr.md#autotoc_md56',1,'weight : 20'],['..//home/runner/work/OST/OST/src/modules/navigator/navigator.fr.md#autotoc_md58',1,'weight : 20'],['..//home/runner/work/OST/OST/src/modules/polar/polar.fr.md#autotoc_md91',1,'weight : 20'],['..//home/runner/work/OST/OST/src/modules/sequencer/sequencer.en.md#autotoc_md93',1,'weight : 20'],['..//home/runner/work/OST/OST/src/modules/sequencer/sequencer.fr.md#autotoc_md132',1,'weight : 20']]],
  ['2_3a_20access_20astrometry_20net_20and_20sep_20as_20an_20internal_20library_20rather_20than_20external_20processes_5',['Goal 2: Access Astrometry.net and SEP as an internal library rather than external processes.',['../md_libs_2stellarsolver_2README.html#autotoc_md177',1,'']]]
];
