--DROP TABLE IF EXISTS PROFILES;
CREATE TABLE IF NOT EXISTS PROFILES (
        MODULETYPE      TEXT NOT NULL,
        PROFILENAME     TEXT NOT NULL,
        ALLVALUES       BLOB,
        PRIMARY KEY("MODULETYPE","PROFILENAME")
);
