CREATE TABLE PROFILES (
        PROFILENAME     TEXT NOT NULL,
        MODULENAME      TEXT NOT NULL,
        PROPERTYNAME    TEXT NOT NULL,
        VALUET          TEXT NOT NULL,
        VALUEN          REAL,
        VALUEB          INTEGER,
        PRIMARY KEY("PROFILENAME","MODULENAME","PROPERTYNAME")
);
