--DROP TABLE IF EXISTS PROFILES;
CREATE TABLE IF NOT EXISTS PROFILES (
        MODULETYPE      TEXT NOT NULL,
        PROFILENAME     TEXT NOT NULL,
        ALLVALUES       BLOB,
        PRIMARY KEY("MODULETYPE","PROFILENAME")
);
--DROP TABLE IF EXISTS PROFILES;
CREATE TABLE IF NOT EXISTS CONFIGURATIONS (
        CONFIGNAME     TEXT NOT NULL,
        MODULELABEL     TEXT NOT NULL,
        MODULETYPE     TEXT NOT NULL,
        PROFILENAME    TEXT NOT NULL,
        PRIMARY KEY("CONFIGNAME","MODULELABEL")
);
INSERT INTO CONFIGURATIONS VALUES ('modules','My Indipanel','Indipanel','default');
INSERT INTO CONFIGURATIONS VALUES ('modules','My Allsky','Allsky','default');
INSERT INTO CONFIGURATIONS VALUES ('modules','My CCD inspector','Inspector','default');
INSERT INTO CONFIGURATIONS VALUES ('modules','My Focuser','Focus','default');
INSERT INTO CONFIGURATIONS VALUES ('modules','My Navigator','Navigator','default');
CREATE TABLE IF NOT EXISTS CATALOGS (
        CATALOG TEXT NOT NULL,
        CODE TEXT NOT NULL,
        RA REAL NOT NULL,
        NS TEXT NOT NULL,
        DEC REAL NOT NULL,
        DIAM REAL,
        MAG REAL,
        NAME TEXT,
        ALIAS TEXT,
        PRIMARY KEY("CATALOG","CODE","RA")
);
--DROP TABLE IF EXISTS OPTICS;
CREATE TABLE IF NOT EXISTS OPTICS (
        NAME     TEXT NOT NULL,
        FOCAL     REAL NOT NULL,
        DIAM     REAL NOT NULL,
        BARLOW REAL NOT NULL,
        FILTER BOOL,
        PRIMARY KEY("NAME")
);
INSERT INTO OPTICS VALUES ('SW200/800',800.0,200.0,1.0,TRUE);
INSERT INTO OPTICS VALUES ('254/1000',1000.0,254.0,1.5,FALSE);
CREATE TABLE IF NOT EXISTS USERS (
        LOGIN     TEXT NOT NULL,
        PW     TEXT NOT NULL,
        GRANT     TEXT NOT NULL, -- 0 : readOnly / 1 : read/write
        PRIMARY KEY("LOGIN")
);
INSERT INTO USERS VALUES ('GUEST','guest','0');
INSERT INTO USERS VALUES ('ADMIN','admin','1');
