DROP TABLE IF EXISTS PROFILES;
CREATE TABLE IF NOT EXISTS PROFILES (
        MODULETYPE      TEXT NOT NULL,
        PROFILENAME     TEXT NOT NULL,
        ALLVALUES       BLOB,
        PRIMARY KEY("MODULETYPE","PROFILENAME")
);
DROP TABLE IF EXISTS CONFIGURATIONS;
CREATE TABLE IF NOT EXISTS CONFIGURATIONS (
        CONFIGNAME     TEXT NOT NULL,
        MODULENAME     TEXT NOT NULL,
        MODULETYPE     TEXT NOT NULL,
        PROFILENAME    TEXT NOT NULL,
        PRIMARY KEY("CONFIGNAME","MODULENAME")
);
INSERT INTO CONFIGURATIONS VALUES ('default','My dummy module','Dummy','default');
INSERT INTO PROFILES VALUES ('Dummy','default','{}');

