--DROP TABLE IF EXISTS PROFILES;
CREATE TABLE IF NOT EXISTS PROFILES (
        MODULETYPE      TEXT NOT NULL,
        PROFILENAME     TEXT NOT NULL,
        ALLVALUES       BLOB,
        PRIMARY KEY("MODULETYPE","PROFILENAME")
);
--DROP TABLE IF EXISTS PROFILES;
CREATE TABLE IF NOT EXISTS CONFIGURATIONS (
        CONFIGNAME     TEXT NOT NULL,
        MODULENAME     TEXT NOT NULL,
        MODULETYPE     TEXT NOT NULL,
        PROFILENAME    TEXT NOT NULL,
        PRIMARY KEY("CONFIGNAME","MODULENAME")
);
INSERT INTO CONFIGURATIONS VALUES ('default','My dummy module','dummy','default');
INSERT INTO CONFIGURATIONS VALUES ('modules','My dummy module','dummy','default');
INSERT INTO CONFIGURATIONS VALUES ('modules','Indipanel','indipanel','default');
INSERT INTO CONFIGURATIONS VALUES ('modules','My Allsky','allsky','default');
INSERT INTO CONFIGURATIONS VALUES ('modules','My CCD inspector','inspector','default');
INSERT INTO CONFIGURATIONS VALUES ('modules','My Focuser','focuser','default');
